### ISSUE TITLE
3D Object Detection code.

### ISSUE THREAD

**Issue by ramapinnimty** [gideontong/AB3DMOT#1]
Can you please point me to the code you used to get the 2D and 3D bounding boxes in the output format you specified [here](https://github.com/gideontong/AB3DMOT#3d-object-detection)?

Thanks
Rama Krishna

**Comment by gideontong** [comment]
Hi, sorry, this is a fork of https://github.com/xinshuoweng/AB3DMOT

Please forward your question there.
